=== mysticol/IHM/IHM/travail_fiche_xml/extension.dtd
<?xml version="1.0" encoding="UTF-8"?>


<!ELEMENT fiche (personnage ,caracteristiquesPrincipales ,caracteristiquesSecondaire , competences )>
<!ELEMENT personnage (info*)>
<!ELEMENT info (#PCDATA)>
<!ELEMENT caracteristique (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT competence (#PCDATA)>
<!ELEMENT caracteristiquesPrincipales (caracteristique+)>
<!ELEMENT caracteristiquesSecondaire (caracteristique+)>
<!ELEMENT competences (categorie+)>
<!ELEMENT categorie (nom, competence+)>

=== mysticol/IHM/IHM/travail_fiche_xml/modele-vampire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fiche SYSTEM "extension.dtd" >
<fiche>
	<personnage>
		<info>joueurs</info>
		<info>nature</info>
		<info>attitude</info>
		<info>chronique</info>
	</personnage>

	<caracteristiquesPrincipales>
		<caracteristique>
		<nom>force</nom>
		</caracteristique>
		<caracteristique>
		<nom>dext</nom>
		</caracteristique>
		<caracteristique>
		<nom>vigueur</nom></caracteristique>
		<caracteristique><nom>astuce</nom></caracteristique>
		<caracteristique><nom>tt</nom></caracteristique>
		<caracteristique><nom>fff</nom></caracteristique>
		<caracteristique><nom>ff</nom></caracteristique>
	</caracteristiquesPrincipales>

<caracteristiquesSecondaire>

<caracteristique><nom>volonte</nom></caracteristique>



</caracteristiquesSecondaire>

<competences> 
<categorie>
<nom>competence</nom>
<competence>bagarre</competence>
</categorie>

</competences>






</fiche>
