=== mysticol/IHM/risque_peril/composant/HADL/src/hadl/m0/descriptionLangage/dtdHadl.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- On a forcément une configuration qui englobe tout. -->
<!ELEMENT configuration (contraintes, proprietes, portConfiguration*, composants, connecteurs, attachements, bindings)>
<!ATTLIST configuration	
				nom CDATA  #REQUIRED
				classPath CDATA #REQUIRED>

<!-- Les contraintes et les proprietes sont de simples donnees -->
<!ELEMENT contraintes (#PCDATA)>
<!ELEMENT proprietes (#PCDATA)>

<!-- Un portConfiguration doit avoir un nom -->
<!ELEMENT portConfiguration EMPTY>
<!ATTLIST portConfiguration
			nom CDATA #REQUIRED>

<!-- Dans les composants d'une configuration, on peut avoir soit des composants simples, -->
<!-- soit des configurations. Il doit y avoir au moins un composant ou configuration. -->
<!ELEMENT composants ( (composant | configuration)+ )>

<!-- Un composant simple doit avoir un nom. -->
<!ELEMENT composant (contraintes, proprietes, port*, service*)>
<!ATTLIST composant	
				nom CDATA #REQUIRED
				classPath CDATA #REQUIRED>

<!-- Un port doit être publique ou privé -->
<!-- Un port doit avoir un nom -->
<!ELEMENT port EMPTY>
<!ATTLIST port
			nom CDATA #REQUIRED
			visibilite (prive|publique) #REQUIRED>

<!-- Un service doit être rattaché à au moins un port d'entrée et seulement un port -->
<!-- en sortie !! pour le moment, un service n'a pas de limitation sur ses ports !! -->
<!-- Un service doit avoir un nom -->
<!ELEMENT service (portService*)>
<!ATTLIST service
				nom CDATA #REQUIRED>

<!-- Un portService doit obligatoirement avoir un nom et un type -->
<!ELEMENT portService EMPTY>
<!ATTLIST portService
				nom CDATA #REQUIRED
				type (in|out) #REQUIRED>


<!-- Il peut y avoir 0..n connecteurs -->
<!ELEMENT connecteurs (connecteur*)>

<!-- Un connecteur est composé d'une ou plusieurs glue(s) -->
<!ELEMENT connecteur (glue+)>
<!ATTLIST connecteur
				nom CDATA #REQUIRED
				classPath CDATA #REQUIRED>

<!-- Une glue est rattachée à plusieurs rolesFrom, et un seul roleTo -->
<!ELEMENT glue (roleFrom+,roleTo)>
<!ATTLIST glue
				nom CDATA #REQUIRED>

<!-- un roleFrom doit avoir un nom -->	
<!ELEMENT roleFrom EMPTY>
<!ATTLIST roleFrom
				nom CDATA #REQUIRED>

<!-- un roleTo doit avoir un nom -->					
<!ELEMENT roleTo EMPTY>
<!ATTLIST roleTo
				nom CDATA #REQUIRED>	
				

<!-- Il peut y avoir 0..n liens d'attachement -->
<!ELEMENT attachements (attachement*)>

<!-- Un attachement lie un portFrom et un roleTo -->
<!ELEMENT attachement (fromComposant, fromPort, toConnecteur, toRole)>
<!ATTLIST attachement
				compoToConnec (oui|non) #REQUIRED>

<!-- ComposantFrom, portFrom, ConnecteurTo et roleTo sont de simples données -->
<!ELEMENT fromComposant (#PCDATA)>
<!ELEMENT fromPort (#PCDATA)>
<!ELEMENT toConnecteur (#PCDATA)>
<!ELEMENT toRole (#PCDATA)>
			

<!-- Il peut y avoir 0..n liens binding -->
<!ELEMENT bindings (binding)*>

<!-- Un binding lie un port composant et un port configuration -->
<!ELEMENT binding (composantToBind, portComposant, portConfig)  >
<!ATTLIST binding
				in (oui|non) #REQUIRED>

<!-- composantToBind, portComposant et portConfig sont de simples donnees -->
<!ELEMENT composantToBind (#PCDATA)>
<!ELEMENT portComposant (#PCDATA)>
<!ELEMENT portConfig (#PCDATA)>

=== mysticol/IHM/risque_peril/composant/HADL/src/hadl/m0/descriptionLangage/exempleCS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "dtdHadl.dtd">
<configuration nom = "CS">

	<contraintes />
	<proprietes />

	<composants>
		<composant nom = "Client">
			<contraintes />
			<proprietes />
			<service nom = "envoie" >
				<portService nom = "3" type = "in" />
				<portService nom = "1" type = "out" />
			</service>
			<service nom = "reception" >
				<portService nom = "2" type = "in" />
			</service>			
		</composant>
		
		<configuration nom="Serveur">
		
			<contraintes></contraintes>
			<proprietes></proprietes>
			
			<composants>
				<composant nom = "ConnectionManager">
					<contraintes />
					<proprietes />
					<service nom = "arriverSortir" >
						<portService nom = "ExternalSocket" type = "in" />
						<portService nom = "ExternalSocket" type = "out" />
					</service>
					<service nom = "dialogSecuDB" >
						<portService nom = "SecurityCheck" type = "in" />
						<portService nom = "SecurityCheck" type = "out" />
					</service>
					<service nom = "dialogDB" >
						<portService nom = "DbQuery" type = "in" />
						<portService nom = "DbQuery" type = "out" />
					</service>					
				</composant>
				
				<composant nom = "DataBase">
					<contraintes />
					<proprietes />
					<service nom = "traiteQuery" >
						<portService nom = "3" type = "in" />
						<portService nom = "1" type = "out" />
					</service>
				</composant>
				
				<composant nom = "Client">
					<contraintes />
					<proprietes />
					<service nom = "envoie" >
						<portService nom = "3" type = "in" />
						<portService nom = "1" type = "out" />
					</service>
					<service nom = "reception" >
						<portService nom = "2" type = "in" />
					</service>			
				</composant>
				
			</composants>
					
			<attachements>
			</attachements>
			
			<connecteurs>
			</connecteurs>
			
			<bindings>
			</bindings>
			
		</configuration>

	</composants>
			
	<attachements>
		<attachement portFrom="nom-prot1" roleTo="nom-port2" />
	</attachements>
	
	
	
	<connecteurs>
		<connecteur nom="con1">
			<glue nom="glu1">
				<roleFrom nom="rf1"/>
				<roleFrom nom="rf2"/>
				<roleTo nom="rt1"/>
			</glue>
		</connecteur>
	</connecteurs>

	<bindings>
		<bindingIn portComposant="pc1" portConfiguration="pcf1" />
		<bindingOut portComposant="pc3" portConfiguration="pcf2"/>
	</bindings>
	
</configuration>

=== mysticol/IHM/risque_peril/composant/HADL/src/hadl/m0/descriptionLangage/exempleHadl.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration SYSTEM "dtdHadl.dtd">
<configuration nom="confGlobal">

	<contraintes />
	<proprietes />
	
	<composants>
		<composant nom="comp1">
			<contraintes />
			<proprietes />
		</composant>
	</composants>
	
	<attachements>
	</attachements>
	
	<connecteurs>
	</connecteurs>	
	
	<bindings>
	</bindings>	
</configuration>
