=== mysticol/IHM/trunk/IHM/travail_fiche_xml/fiche.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT fiche (jeu,personnage,caracteristiquesPrincipales,caracteristiquesSecondaire, 
competences, pouvoirs, barreDeVie, equipement, divers)>

<!ELEMENT personnage (nom, poid, taille, age, concept, info*, xp)>

<!ELEMENT jeu (univers, campagne, system?)>
<!ELEMENT univers (#PCDATA)>
<!ELEMENT campagne (#PCDATA)>
<!ELEMENT systeme (#PCDATA)>

<!ELEMENT nom (#PCDATA)>
<!ELEMENT info (nom, valeur)>

<!ELEMENT poid (#PCDATA)>
<!ELEMENT taille (#PCDATA)>
<!ELEMENT concept (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT xp (#PCDATA)>
<!ELEMENT desc (#PCDATA)>


<!ELEMENT caracteristiquesPrincipales (caracteristique+)>
<!ELEMENT caracteristique (nom, valeur, jauge?, consommable?)>
<!ELEMENT valeur (#PCDATA)>
<!ELEMENT jauge (#PCDATA)>
<!ELEMENT consommable (#PCDATA)>


<!ELEMENT caracteristiquesSecondaire (caracteristique+)>
<!ELEMENT competences (categorie+)>

<!ELEMENT competence (nom, valeur)>


<!ELEMENT categorie (nom, competence+)>

<!ELEMENT pouvoirs (pouvoir*)>
<!ELEMENT pouvoir (nom,desc?)>

<!ELEMENT barreDeVie (#PCDATA)>
<!ELEMENT equipements (equipement*)>
<!ELEMENT equipement (nom, desc?)>



<!ELEMENT divers (#PCDATA)>

=== mysticol/IHM/trunk/IHM/travail_fiche_xml/fiche.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fiche SYSTEM "fiche.dtd" >
<fiche>
  <personnage>
    <nom>nom</nom>
    <poid>poid</poid>
    <taille>taille</taille>
    <age>age</age>
    <concept>concept</concept>
    <info>
      <nom>nom</nom>
      <valeur>valeur</valeur>
    </info>
    <xp>xp</xp>
  </personnage>
  <caracteristiquesPrincipales>
    <caracteristique>
      <nom>nom</nom>
      <valeur>valeur</valeur>
      <jauge/>
      <consommable>true</consommable>
    </caracteristique>
  </caracteristiquesPrincipales>
  <caracteristiquesSecondaire/>
  <competences/>
  <pouvoirs/>
  <barreDeVie/>
  <equipement/>
  <divers/>
</fiche>
